fix "RuntimeError: generator didn't yield"
This was reported to happen if a C++ compiler is not installed but C++ source code
is included:

Traceback (most recent call last):
  File "/home/dgilbert/qemu/meson/mesonbuild/mesonmain.py", line 131, in run
    return options.run_func(options)
  File "/home/dgilbert/qemu/meson/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/home/dgilbert/qemu/meson/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/home/dgilbert/qemu/meson/mesonbuild/msetup.py", line 215, in _generate
    intr.backend.generate()
  File "/home/dgilbert/qemu/meson/mesonbuild/backend/ninjabackend.py", line 509, in generate
    self.generate_target(t)
  File "/home/dgilbert/qemu/meson/mesonbuild/backend/ninjabackend.py", line 827, in generate_target
    obj_list.append(self.generate_single_compile(target, src, False, [], header_deps))
  File "/home/dgilbert/qemu/meson/mesonbuild/backend/ninjabackend.py", line 2329, in generate_single_compile
    commands = self._generate_single_compile(target, compiler, is_generated)
  File "/home/dgilbert/qemu/meson/mesonbuild/backend/ninjabackend.py", line 2263, in _generate_single_compile
    commands += self.generate_basic_compiler_args(target, compiler, no_warn_args)
  File "/home/dgilbert/qemu/meson/mesonbuild/backend/backends.py", line 677, in generate_basic_compiler_args
    commands += compiler.get_option_compile_args(copt_proxy)
  File "/home/dgilbert/qemu/meson/mesonbuild/compilers/cpp.py", line 329, in get_option_compile_args
    args.append(self._find_best_cpp_std(std.value))
  File "/home/dgilbert/qemu/meson/mesonbuild/compilers/cpp.p^C, line 150, in _find_best_cpp_std
    if self._test_cpp_std_arg(cpp_std_value):
  File "/home/dgilbert/qemu/meson/mesonbuild/compilers/cpp.py", line 116, in _test_cpp_std_arg
    with self.compile(CPP_TEST, extra_args=[cpp_std_value], mode='compile') as p:
  File "/usr/lib64/python3.6/contextlib.py", line 83, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield

As the minimal fix, just ensure that the contextmanager always yields
something, as in the (mostly unrelated) 0.56 commit d326c87fe ("compilers:
Use a distinct type for compile/link results", 2020-09-24).